### PR TITLE
Check if we are connected before disconnecting

### PR DESCRIPTION
**Pull request by JoyfulReaper**

### CODE REVIEW

**Comment by Yucked** [comment]
Thank you but often time when discord has a hiccup, lavalink drops voice gateway connection which leads to Victoria sending requests to Lavalink and lavalink refusing to play anything because Victoria isn't "connected" and removing that check allows users to disconnect in these scenarios.

**Comment by JoyfulReaper** [comment]
> Thank you but often time when discord has a hiccup, lavalink drops voice gateway connection which leads to Victoria sending requests to Lavalink and lavalink refusing to play anything because Victoria isn't "connected" and removing that check allows users to disconnect in these scenarios.

I'm not sure I understand, I added the check, not removed it, and this fixes the issue for me

**Comment by Yucked** [comment]
Remind me again, what issue were you facing?

**Comment by JoyfulReaper** [comment]
When my Discord Bot shutdown and the IHost was disposed I would receive an exception from the DisposeAsync() method in LavaNode.cs becasuse DisconnectAsync() is called without checking to see if IsConnected is true or not. If IsConntect is false than an exception is thrown in on line 205: throw new InvalidOperationException("Can't disconnect when client isn't connected.");

This just checks to make sure isConnceted is true before calling DisconnectAsync()

I also had a similair issue in LavaSocket.cs, (on Line 48) but that files doesn't seem to exist in the V5 branch anymore.

I am using Victoria 5.1.11 and patched that to fix my issue against commit 9f19acba1d0a29aac68fd6f032c4262c02c4c228 on my fork to resolve the issue.

This patch should prevent this from re-occurring in the next release

**Comment by SteveModz** [comment]
I am having this same issue from time to time! :(

**Comment by Yucked** [comment]
> in LavaNode.cs becasuse DisconnectAsync() is called without checking to see if IsConnected is true or not.

Dunno where you got that from? `DisconnectAsync` checks whether or not your are connected before disconnecting
https://github.com/Yucked/Victoria/blob/9f19acba1d0a29aac68fd6f032c4262c02c4c228/src/LavaNode.cs#L196-L214


> If IsConntect is false than an exception is thrown in on line 205: throw new InvalidOperationException("Can't disconnect when client isn't connected.");

Which makes sense...? Why would you disconnect where there is no active websocket connection.

> I also had a similair issue in LavaSocket.cs, (on Line 48) but that files doesn't seem to exist in the V5 branch anymore.

https://github.com/Yucked/Victoria/blob/9f19acba1d0a29aac68fd6f032c4262c02c4c228/src/LavaSocket.cs#L47-L56

**Comment by JoyfulReaper** [comment]
I'm closing this pull request since my issues are in 5.1.11 and I don't want to make this more complicated then it needs to be...

**Pull request closed without merging**
