### PR TITLE
Added virtual modifiers to the public fields of LavaTrack

### PR DESCRIPTION
**Pull request by TheMulti0**
This pull request adds `virtual` modifiers to the public fields of `LavaTrack`, for easy override in case of custom implementations of LavaTrack.

### CODE REVIEW

**Comment by Yucked** [comment]
This seems like a single user-specific case.

**Comment by TheMulti0** [comment]
@Yucked no, it's a follow up of the previous pull request that was supposed to contain these changes as well.

**Comment by TheMulti0** [comment]
Update: Hash is public, that makes custom track implementations change the Hash property which is critical for a functioning track object.

**Comment by Yucked** [comment]
You can inherit from LavaTrack, add your own properties but the base properties can't be virtual since that info is stored in hash as well and should match. And I haven't seen any user wanting to override that info besides you.

**Comment by TheMulti0** [comment]
> You can inherit from LavaTrack, add your own properties but the base properties can't be virtual since that info is stored in hash as well and should match.

Because I am changing the base properties I want to change the hash as well, hence why I made it public.

> And I haven't seen any user wanting to override that info besides you.

If it's necessary, I can describe my case of use and I'm sure you will understand why is that addition critical to me.

<br />
Also, these additions do not limit functionality of Victoria, so I can not see why even for a single man this should not be merged.

**Comment by Yucked** [comment]
> Because I am changing the base properties I want to change the hash as well, hence why I made it public. If it's necessary, I can describe my case of use and I'm sure you will understand why is that addition critical to me.

Describe what you're planning to do. If you're planning on sending a custom hash to lavalink then I'm not sure if that will work. If a lot of users start doing it and things start breaking, I can't provide support for it and neither can a lot of people in my server hence this PR is only specific to you.

**Comment by TheMulti0** [comment]
> Describe what you're planning to do.

I am going to create a special track that is provided with specific information that is not retrieved from Lavalink, and that information has all of the data that the base properties of LavaTrack have. Of course that in order to get the stream of that track and actually play it I later on search it on YouTube (on the fly, when it's about to play), I still want the track to be a LavaTrack and behave like one (have the right metadata as if it was brought from Lavalink) since my code and Victoria works with LavaTrack and I prefer to leave it like that

>  If you're planning on sending a custom hash to lavalink then I'm not sure if that will work.

I have reconsidered what I have to do, and decided making the properties `virtual` is enough, and I have no need in the Hash property.

**Comment by TheMulti0** [comment]
There you go, I reverted the hash property meaning that it's now completely internal

**Comment by Earu** [comment]
@TheMulti0 Should probably close this now.

**Comment by TheMulti0** [comment]
I'd be happy if you reconsider this perhaps in v5.

**Pull request closed without merging**
