### PR TITLE
Fix PlayAsync Start/EndTime bug

### PR DESCRIPTION
**Pull request by flipch**

### CODE REVIEW

**Comment by flipch** [comment]
@Yucked Any eta for when this would be released?

**Comment by Yucked** [comment]
> @Yucked Any eta for when this would be released?

Can you also change csproj - 
Increment the patch by one and describe changes in change notes

**Comment by flipch** [comment]
> > @Yucked Any eta for when this would be released?
> 
> Can you also change csproj -
> Increment the patch by one and describe changes in change notes

I assumed the change notes was the PackageReleaseNotes, let me know if it's in a different place.

**Comment by Yucked** [comment]
> > > @Yucked Any eta for when this would be released?
> 
> > 
> 
> > Can you also change csproj -
> 
> > Increment the patch by one and describe changes in change notes
> 
> 
> 
> I assumed the change notes was the PackageReleaseNotes, let me know if it's in a different place.
> 
> 

No, you're right. It's PackageReleaseNotes.

**Pull request merged**
